"""SDK for the Genesys Subsetting API (climate indicators and clustering of accessions)."""

from subsetting_sdk.catalog import IndicatorCatalog, normalize_text
from subsetting_sdk.client import SubsettingClient
from subsetting_sdk.exceptions import (
    CoreCollectionError,
    IndicatorNotFoundError,
    IndicatorPeriodNotFoundError,
    NoMatchingDataError,
    SubsettingApiError,
    SubsettingConnectionError,
)
from subsetting_sdk.models import (
    AnaloguesResult,
    CellIndicatorData,
    ClusteringAlgorithm,
    ClusteringHyperparameters,
    ClusterRequest,
    ClusterResult,
    ClusterRow,
    CoreCollectionResult,
    CropCellIds,
    FilteredCrop,
    Indicator,
    IndicatorCategory,
    IndicatorDataResult,
    IndicatorFilter,
    IndicatorPeriod,
    IndicatorRange,
    IndicatorRangesResult,
    IndicatorType,
    MonthWindow,
    SubsetResult,
)

__all__ = [
    "AnaloguesResult",
    "CellIndicatorData",
    "ClusterRequest",
    "ClusterResult",
    "ClusterRow",
    "ClusteringAlgorithm",
    "ClusteringHyperparameters",
    "CoreCollectionError",
    "CoreCollectionResult",
    "CropCellIds",
    "FilteredCrop",
    "Indicator",
    "IndicatorCatalog",
    "IndicatorCategory",
    "IndicatorDataResult",
    "IndicatorFilter",
    "IndicatorNotFoundError",
    "IndicatorPeriod",
    "IndicatorPeriodNotFoundError",
    "IndicatorRange",
    "IndicatorRangesResult",
    "IndicatorType",
    "MonthWindow",
    "NoMatchingDataError",
    "SubsetResult",
    "SubsettingApiError",
    "SubsettingClient",
    "SubsettingConnectionError",
    "normalize_text",
]
