"""File-system session management.

The system keeps a single temporary root folder (``TMP_DIR``). Inside it, one
folder per session is created with two sub folders:

* ``inputs``  - every file uploaded by the user.
* ``outputs`` - every file generated by the system (CSV exports, markdown...).
"""

import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from core.logger import get_logger

logger = get_logger(__name__)

# Characters allowed in a session folder name. Anything else is replaced by "_".
_SAFE_SESSION_ID = re.compile(r"[^A-Za-z0-9_\-]")


@dataclass(frozen=True)
class SessionPaths:
    """Folders that belong to a single session.

    Attributes:
        session_id: Sanitised identifier of the session.
        root: ``<tmp>/<session_id>``.
        inputs: ``<tmp>/<session_id>/inputs``.
        outputs: ``<tmp>/<session_id>/outputs``.
    """

    session_id: str
    root: Path
    inputs: Path
    outputs: Path


class SessionManager:
    """Create and resolve the folders of every session under the temporary root."""

    def __init__(self, tmp_dir: Path) -> None:
        """Initialise the manager and make sure the temporary root exists.

        Args:
            tmp_dir: Root folder where session folders are created.
        """
        self.tmp_dir = Path(tmp_dir)
        self.tmp_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def sanitize_session_id(session_id: str) -> str:
        """Turn any session identifier into a safe folder name.

        Args:
            session_id: Raw identifier (e.g. the Gradio ``session_hash``).

        Returns:
            The identifier with unsafe characters replaced by ``_``.
        """
        return _SAFE_SESSION_ID.sub("_", session_id.strip()) or "default"

    def get_paths(self, session_id: str) -> SessionPaths:
        """Return the folders of a session, creating them if they do not exist.

        Args:
            session_id: Identifier of the session.

        Returns:
            A ``SessionPaths`` with ``root``, ``inputs`` and ``outputs`` created.
        """
        safe_id = self.sanitize_session_id(session_id)
        root = self.tmp_dir / safe_id
        inputs = root / "inputs"
        outputs = root / "outputs"

        # Create the whole tree in one go; ``exist_ok`` makes the call idempotent.
        inputs.mkdir(parents=True, exist_ok=True)
        outputs.mkdir(parents=True, exist_ok=True)

        return SessionPaths(session_id=safe_id, root=root, inputs=inputs, outputs=outputs)

    def store_input_file(self, session_id: str, source: Path) -> Path:
        """Copy a file uploaded by the user into the session ``inputs`` folder.

        Args:
            session_id: Identifier of the session.
            source: Path of the uploaded file (usually a Gradio temporary file).

        Returns:
            Path of the copy inside ``inputs``.

        Raises:
            FileNotFoundError: If ``source`` does not exist.
        """
        source = Path(source)

        # Refuse silently-missing files: a wrong path must surface immediately.
        if not source.is_file():
            raise FileNotFoundError(f"Uploaded file not found: {source}")

        paths = self.get_paths(session_id)
        destination = paths.inputs / source.name

        # Avoid overwriting a previous upload with the same name by adding a suffix.
        counter = 1
        while destination.exists():
            destination = paths.inputs / f"{source.stem}_{counter}{source.suffix}"
            counter += 1

        shutil.copy2(source, destination)
        logger.info("Stored input file %s for session %s", destination.name, paths.session_id)

        return destination

    def list_input_files(self, session_id: str) -> list[Path]:
        """List every file currently stored in the session ``inputs`` folder.

        Args:
            session_id: Identifier of the session.

        Returns:
            Sorted list of file paths.
        """
        paths = self.get_paths(session_id)
        return sorted(path for path in paths.inputs.iterdir() if path.is_file())
